### ISSUE TITLE
Feat: Change surrounding x with 2x

### ISSUE THREAD

**Issue by nicolaiskogheim** [tpope/vim-unimpaired#101]
In bash you sometimes want double paren's or brackets, like  
`(( 2 + 2 )) ` and `[[ -x "$var" ]]`

In the latter case it is sometimes only necessary with one pair of brackets, and I need to switch.

If i type `cs[2` my `[ xyz ]` becomes `2 xyz 2` which may or may not be useful for anyone, so maybe we could use count to specify how many of something we want.

**Comment by alcesleo** [comment]
Shouldn't this be in the [surround](https://github.com/tpope/vim-surround) plugin instead?

**Comment by nicolaiskogheim** [comment]
Yes, sorry. Total brainfairt. Thank you.

**Comment by tpope** [comment]
FYI You can do `ysa]]`. Count interface is cute but doesn't seem worth it.

**Comment by nicolaiskogheim** [comment]
This covers all my needs, thank you!
