### ISSUE TITLE
vim-unimpaired makes barfing/slurping in paredit slow

### ISSUE THREAD

**Issue by vicvicvic** [tpope/vim-unimpaired#104]
When vim-unimpaired and [paredit.vim](https://github.com/vim-scripts/paredit.vim) are installed and paredit's shortmaps are enabled (so that <kbd>></kbd> and <kbd><</kbd> barf/slurp in normal mode), there is a very noticeable delay before anything happens (about 1 second).

I have installed vim-unimpaired and paredit like so (minimal .vimrc):

```vim
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'

Plugin 'vim-scripts/paredit.vim'
Plugin 'tpope/vim-unimpaired'

call vundle#end()

let g:paredit_shortmaps = 1
```

This does not happen if shortmaps are not enabled (so that you have to press <kbd>&lt;Leader&gt;<</kbd> etc). Only seems to affect slurping and barfing and not other shortmapped commands (e.g. <kbd>J</kbd>, <kbd>O</kbd>).

Running vim 7.4.884 on OS X 10.11 (installed via Homebrew).

**Comment by tpope** [comment]
That's because of the overlap with unimpaired.vim's `>p` and `<p`. I think overriding partial key sequences (The built-in `<` *always* requires an additional keypress) with standalone commands is an antipattern, so I'm putting the burden on paredit. `<nowait>` might prove useful.

**Comment by midnio** [comment]
```vim
nnoremap <leader>>p <Nop>
nnoremap <leader><p <Nop>
```
This is should work.

**Comment by tpope** [comment]
The solution I wasn't explicit enough about in the above comment is for paredit to add `<nowait>` to its `<` and `>` maps.

**Comment by midnio** [comment]
It's a script so it's just a mirror and we can't commit or pull request.

**Comment by tpope** [comment]
You can email the author.

**Comment by tpope** [comment]
Also if you're using https://github.com/vim-scripts/paredit.vim, don't. The vim-scripts scraper has been broken for half a decade.
