### ISSUE TITLE
`[<space>` and `]<space>` don't respect the "r" and "o" settings in `'formatoptions'`

### ISSUE THREAD

**Issue by gwerbin** [tpope/vim-unimpaired#107]
Maybe this behavior is intentional, but I was expecting these mappings to mirror the settings used by `o` and `O`.

Is this something that sounds feasible? Is this even something other people might want?

In my `.vimrc` I have

    nnoremap <silent> [<space> :normal O<esc>j
    nnoremap <silent> ]<space> :normal o<esc>k

which is a good approximation for my use (since I rarely want to use a count here).

I just spent a little while trying to figure out a version that returns the cursor to the right place, but I couldn't figure it out. I'm stuck on how to properly emulate `[count]o<esc>` inside a function. There's something weird about how Vim passes around counts...

**Comment by tpope** [comment]
This behavior is very deliberate, as the reason I bothered adding these to begin with was `o<Esc>` was forcing comment characters where I didn't want them. I'm not sure why anyone want want a blank comment line.

**Comment by tpope** [comment]
This behavior is very deliberate, as the reason I bothered adding these to begin with was `o<Esc>` was forcing comment characters where I didn't want them. I'm not sure why anyone want want a blank comment line.

**Comment by gwerbin** [comment]
Fair enough. I tend to use a lot of paragraph breaks when I write in plain text, and I like keeping a continuous line of comment characters to connect them.
