### ISSUE TITLE
Add shortcuts for toggling background (dark/light)?

### ISSUE THREAD

**Issue by schoettl** [tpope/vim-unimpaired#113]
What do you think of adding `[ob`, `]ob` for toggling the `background` option?

Currently I have a custom mapping (but I would prefer using unimpaired):
```
nnoremap <F6> :let &background = ( &background == "dark" ? "light" : "dark" )<CR>
```

**Comment by tpope** [comment]
It's already there.

**Comment by schoettl** [comment]
Oops, you're right, sorry. I did not find it in the README but it is in the Vim doc.

Thank you!
