### ISSUE TITLE
[l ]l doesn't work with repeat.vim

### ISSUE THREAD

**Issue by vaxXxa** [tpope/vim-unimpaired#115]
`[e` and `]e` works fine
`[Space` and `]Space` works fine

`[l` and `]l` – doesn't (for example, in syntastic location list)

**Comment by HaleTom** [comment]
Just letting you know that it also doesn't work with [repmo.vim - repeat motions for which a count was given](https://github.com/vim-scripts/repmo.vim)

**Comment by tpope** [comment]
`[l` and `]l` don't change anything, so it doesn't make sense for `.` to repeat them.
