### ISSUE TITLE
remapping cob in my .vimrc

### ISSUE THREAD

**Issue by gauteh** [tpope/vim-unimpaired#120]
This is probably not an unimpaired bug, but more of a support request so feel free to close if offtopic:

I have a custom ToggleBackground() function that does a little more than `cob`. I have installed `vim-unimpaired` using `execute pathogen#infect()` at the top of my `.vimrc`. However, for the life of me, I am not able to set `cob` to map to my function, I've tried:

```
nnoremap cob :call ToggleBackground()<cr>
nmap cob :call ToggleBackground()<cr>
```

but it does not work, if I use e.g. `cbb` it works just fine. Do you have any hints as to how I could achieve this?

**Comment by tpope** [comment]
You can get around it by sticking it after an `au VimEnter *` or putting it in `.vim/after/plugin/unimpaired.vim`.

Ideally, Unimpaired wouldn't be stomping on existing maps, but retrofitting that onto the numerous maps it provides is, well, annoying.

**Comment by gauteh** [comment]
Alright, thanks.
