### ISSUE TITLE
Leaving the insert mode with Ctrl-C doesn't reset `yo` paste settings

### ISSUE THREAD

**Issue by adambyrtek** [tpope/vim-unimpaired#124]
This is caused by the expected behaviour of the `InsertLeave` autocmd:

> When leaving Insert mode.  Also when using CTRL-O i_CTRL-O.  But not for i_CTRL-C.

Potential solution would be to override C-c in insert mode, but this is not ideal, so I'm wondering if there are any better options? I'm happy to work on a PR if there is an approach that could be acceptable.

**Comment by tpope** [comment]
It's working for me, and I'm not exactly clear why. At any rate overriding `<C-c>` is a nonstarter because paste mode disables maps.

**Comment by adambyrtek** [comment]
I tried NeoVim and Vim 7.4 and both are stuck with paste enabled after `C-c`. How about restoring the paste setting using normal mode `CursorMoved` as a workaround? This would be triggered only once after first motion (or not at all if `InsertLeave` is triggered first) since the handler deletes the whole autocmd group at the end.

**Comment by tpope** [comment]
Finally ran into this myself. Fixed in 80ab990c7ff7251f43262aae4b60ff6eff2ef3a4.
