### ISSUE TITLE
Don't trigger more prompt for cox mapping

### ISSUE THREAD

**Issue by y** [tpope/vim-unimpaired#126]
Using my standard 80 column wide window, the `cox` mapping always triggers the more prompt for me. I need to set my window size to at least 101 columns for it to go away. One solution is to use `<silent>`, but I can see the need for echoing out the command for these mappings. The other solution is to use a `<expr>` to shorten the executed mapping. This works for me:

    diff --git a/plugin/unimpaired.vim b/plugin/unimpaired.vim
    index cc401af..3dec115 100644
    --- a/plugin/unimpaired.vim
    +++ b/plugin/unimpaired.vim
    @@ -242,7 +242,7 @@ call s:option_map('s', 'spell', 'setlocal')
    call s:option_map('w', 'wrap', 'setlocal')
    nnoremap [ox :set cursorline cursorcolumn<CR>
    nnoremap ]ox :set nocursorline nocursorcolumn<CR>
    -nnoremap cox :set <C-R>=&cursorline && &cursorcolumn ? 'nocursorline nocursorcolumn' : 'cursorline cursorcolumn'<CR><CR>
    +nnoremap <expr> cox ':set ' . (&cursorline && &cursorcolumn ? 'nocursorline nocursorcolumn' : 'cursorline cursorcolumn').'<CR>'
    nnoremap [ov :set virtualedit+=all<CR>
    nnoremap ]ov :set virtualedit-=all<CR>
    nnoremap cov :set <C-R>=(&virtualedit =~# "all") ? 'virtualedit-=all' : 'virtualedit+=all'<CR><CR>

**Comment by tpope** [comment]
Yeah I do want the command echoed. Assuming your solution preserves that I'll merge if you make a PR.
