### ISSUE TITLE
Relative location and quickfix list movements

### ISSUE THREAD

**Issue by DerWeh** [tpope/vim-unimpaired#133]
As all other movements with `[` and `]` are relative, it would be great to also have this for `[l` and `[q` and more consistent.

I know this might be quite hard to implement, but I think this would really be great in combination with plugins like [ALe](https://github.com/w0rp/ale) or [Neomake](https://github.com/neomake/neomake), which constantly update your location list.

**Comment by hoclun-rigsep** [comment]
TIL: Since some recent vim version we now have `:cafter`, `:lafter`, and friends.

**Comment by tpope** [comment]
`:cafter` and friends have 2 limitations that prevent them from being drop in `:cnext` and friends replacements:

* Quickfix entries must be sorted.
* Can't navigate multiple files.

And I don't think a custom implementation can work around either of these. So I think this request is dead in the water, but I'll leave #195 open to cover the possibility of adding new maps.
