### ISSUE TITLE
`co` mappings no longer work in some fugitive buffers

### ISSUE THREAD

**Issue by tommcdo** [tpope/vim-unimpaired#135]
In 3a7759075cca5b0dc29ce81f2747489b6c8e36a7, the option toggle mappings were change from `co` to `=o`. It looks like the fallback `co` mapping is only created if there is no other mapping to `co` already defined. While I think that's a good idea in general, it has the side effect that the presence of the `co` mapping in fugitive buffers suppresses the unimpaired mapping.

I'm not sure if this needs to be fixed, or if I should just retrain my fingers to use `=o`. It's a bit of a bummer to me, as I occasionally like to turn on `'cursorline'` using `coc` while reviewing unstaged changes the `:Gstatus` buffer, and `=oc` is markedly harder to type than `coc`.

I'm okay if the response is "tough, deal with it"; if nothing else, this issue can act as a resource for others to Google search for.

**Comment by tpope** [comment]
Somehow never noticed this conflict before, but this means that *before* the Unimpaired change, the problem went the other way, with Fugitive's `co` being shadowed by a bunch of Unimpaired maps. If anything, this *increases* the priority of finishing the transition. :grin:
