### ISSUE TITLE
a way to rebind =o binds?

### ISSUE THREAD

**Issue by unphased** [tpope/vim-unimpaired#143]
I have a function associated with `=` in normal mode (`vertical res +8`, increase width of window) and the recent change in bindings makes this `=` have a lag now.

I cannot think of a better way to address this without making a fork of the repo. I really want to avoid having a fork for half of my plugins... 

Should I make a PR where this bind can be edited with a config variable?

**Comment by tpope** [comment]
Adding `<nowait>` to your map should allow it to take precedence.
