### ISSUE TITLE
Is it possible to override ]e an [e?

### ISSUE THREAD

**Issue by JesseLeite** [tpope/vim-unimpaired#145]
Is it possible for me to override `]e` and `[e` mappings (I use `<C-j>` and `<C-k>` personally, and want to reclaim these mappings for Emmet:

```
nmap ]e <plug>(emmet-move-next)
nmap [e <plug>(emmet-move-prev)
```

Having trouble though.  Is it because they are implemented with `exe`?

**Comment by tpope** [comment]
There wasn't a good way to do this ... until now. I just pushed up a new override system, complete with documentation, that I've been sitting on. See if you can figure it out now.

**Comment by JesseLeite** [comment]
Hey @tpope thanks for this!  Look at your commit now and I understand the global overrides, like changing all `[` and `]` to arrow brackets 👌  Where I'm unclear is single mapping overrides.  I love most of unimpaired's default mappings, I just want to override `]e` / `[e`.  Is that what you intended?

**Comment by tpope** [comment]
The operative phrase is "*a complete map* or a prefix thereof".

**Comment by JesseLeite** [comment]
Right 🙂 

>The key can be either a complete map or a prefix thereof, and the value is the key sequence to use instead, or an empty string to disable the mapping or mappings entirely.

So I tried this:

```
let g:nnoremap = {"[e": "", "]e": ""}
```

Where I've set keys as complete `[e` and `]e` mappings, and values as empty strings to disable.  Am I understanding correctly?  Doesn't seem to be taking.

**Comment by tpope** [comment]
Deciding on the variable names is why I've been sitting on this for so long.

**Comment by JesseLeite** [comment]
Ah there we go!  Fair enough regarding the naming.  It's open source, you reserve the right to do anything without warranty 👌 Anyway, thank you for your packages... You are a wonderful human being!

**Comment by justinmk** [comment]
So how does one restore the `co` prefix (since https://github.com/tpope/vim-unimpaired/commit/bacf1543cc957d47aa70c1dc0bcf99392925b008)? 

I tried this (and the converse):

```
let g:nremap = {"=": "co"}
let g:xremap = {"=": "co"}
let g:oremap = {"=": "co"}
```

What was the motivation for the `=o` change? It feels like a regression in ergonomics and mnemonics.

**Comment by tpope** [comment]
If you have a better name feel free to suggest it. The semantic is "I've remapped `c` to `=`, so please put any additional `=` maps on `c` too". Which *isn't* what you did and *isn't* what you want, as it'll break `=p` too. You could `{"=o": "co"}` if you wanted but really you should just`nmap co =o` and be done with it. The variable is more for foreign and alternative keyboard layouts than it is for micromanaging individual maps.

I'm moving the map to reduce namespace sprawl, as we've gone from a bracket only plugin to all over the place. I'd like to reduce it to three. Admittedly `=` is a bit harder to reach, but I think using a third punctuation mark is more natural when you zoom out from the option toggles. (The most natural choice would be `\`, but I don't think we can get away with taking the default leader.)

Plus, Netrw has that stupid `<nowait>` map on `c`. It's a terrible choice, practically speaking, for anything universal.

**Comment by tpope** [comment]
A week in I'll admit I hate this too. If it wasn't for the netrw issue I'd have reverted by now. I see `yo` doesn't have that problem, perhaps we move our own `yo` somewhere else and take that? What a pain.

**Comment by tpope** [comment]
We could use `[O` and `]O` for `yO` and `yo`, and then add `=O` for the previously unhandled "don't add a new line at all" edge case. Or dump it in the option namespace as `[op`, `]op`, and `yop`.

**Comment by tpope** [comment]
Let's continue discussion about the option toggle map in #150.

**Comment by adberard** [comment]
What is exactly the code to write in init.vim to remap ? Here is what I tryed so far, without result
` let g:nremap = {"[q": "", "]q": ""}
  let g:xremap = {"[q": "", "]q": ""}
  let g:oremap = {"[q": "", "]q": ""}
  let g:nremap = {"q": ""}

nunmap [q
nunmap ]q
noremap [q :ALEPrevious<cr>
noremap ]q :ALENext<cr>
map [q :ALEPrevious<cr>
map ]q :ALENext<cr>
`
