### ISSUE TITLE
"co" and "=o" mappings now override

### ISSUE THREAD

**Issue by flemingfleming** [tpope/vim-unimpaired#155]
I used to use `g:nremap` to stop `co` overriding my personal `co` mapping, but removed that when the default was changed to `=o`. 

However since the recent change to bring back `co`, the mapping now [unconditionally overrides](https://github.com/tpope/vim-unimpaired/blob/master/plugin/unimpaired.vim#L288) any mapping for `co` in a user's vimrc, forcing the user to move any mapping to VimEnter. The [same applies](https://github.com/tpope/vim-unimpaired/blob/master/plugin/unimpaired.vim#L281) for `=o`

**Comment by pacholik** [comment]
There should be also a check for `omap o`.

**Comment by tpope** [comment]
Feel free to add one. I almost hate to ask but doesn't an o omap play poorly with `yo` as well?
