### ISSUE TITLE
Unmapping [x ]x

### ISSUE THREAD

**Issue by dmitriyK1** [tpope/vim-unimpaired#159]
I have a conflicting keybindings of unimpaired and rhysd/conflict-marker.vim
Because I don't use [x ]x from unimpaired I'd like to unmap it, but I'm getting errors while trying to do so in .vimrc ('No such mapping' error)
How is it possible to unmap these keybindings so other plugin could override them?
Thanks in advance.

**Comment by tpope** [comment]
You're in luck. I've been thinking about moving encoding maps to `<` and `>`, and this has prompted me to finally pull the trigger. I've left the old maps behind for backwards compatibility, but only if another plugin hasn't claimed them.

**Comment by tpope** [comment]
I had to revert this. You can achieve the desired unmap by doing `autocmd VimEnter * ...` in your vimrc or by unmapping directly in `after/plugin/unimpaired.vim`.

**Comment by dmitriyK1** [comment]
Thanks, I'll try this approach instead then
Why have you reverted btw?

**Comment by tpope** [comment]
Try pulling again, I forgot to push my changes.

You probably want to `nunmap` and `xunmap` rather than `unmap`.

**Comment by dmitriyK1** [comment]
Yeah, I've updated and now it works, thanks!
