### ISSUE TITLE
Shifting delay with the new angle bracket mappings in visual mode

### ISSUE THREAD

**Issue by carloabelli** [tpope/vim-unimpaired#160]
I use `<` and `>` in visual mode frequently to shift code.

Unfortunately the new angle bracket mappings introduced in bdd88b9ea6d22c46db880821ceca03e3f21686a5 cause a slight but noticeable delay.

Is there a way to opt-out of the new angle bracket mappings?

**Comment by tpope** [comment]
For years we have had `<p` and `>p` mappings. Those don't cause a delay?

**Comment by carloabelli** [comment]
Since those are normal mode mappings they do not cause a delay when shifting in visual mode.

**Comment by tpope** [comment]
Crap, I hadn't considered that. I might have to revert that change.

**Comment by carloabelli** [comment]
This is particularly painful if you `vnoremap > >gv` and `vnoremap < <gv` for quickly repeated indenting

**Comment by nfischer** [comment]
@tpope did you forget to also revert bdd88b9ea6d22c46db880821ceca03e3f21686a5?

**Comment by tpope** [comment]
Dang it.

**Comment by nfischer** [comment]
Thanks, works great now!
