### ISSUE TITLE
The vim '<n>P' and '<n>p' commands are acting oddly with this plugin and vimoutliner

### ISSUE THREAD

**Issue by jdubiner** [tpope/vim-unimpaired#162]
Investigating. There seems to be an interaction with vimoutliner and vim-uninpaired having to do with <n>p

for example:

4p
or 4P
is giving me unexpected results.  Not sure which plugin is causing the problem; it seems to be an interaction of the two.

edit:  I think it's with vim-unimpaired.  Other plugins are working fine.

Specifically, in my case, with 'this is a test' in the yank buffer, if I go to a line with 'This is not a test' and
do 4P (note uppercase) it behaves the same as 4p

I will continue to investigate.

Thanks!

**Comment by tpope** [comment]
What does `:verbose nmap p` / `:verbose nmap P` report?

**Comment by jdubiner** [comment]
Hi Tim,

The issue is with vimoutliner.  I'm going to close the issue...
Thanks for your help; the :verbose nmap command is really useful

The file in vimoutliner is: vimoutliner/plugin/votl_smart_paste.vim

I believe the problematic line is:

map <buffer>P ]P

I commented that out and everything is working fine now.
