### ISSUE TITLE
Disabling maps

### ISSUE THREAD

**Issue by midnio** [tpope/vim-unimpaired#163]
Is there a way to disable specified maps like `>p`?

**Comment by tpope** [comment]
There's a system I removed from the documentation because it was confusing:

    let g:nremap = {'<p': '', '>p': ''}

But please do follow up with paredit about adding the `<nowait>` thing.

**Comment by midnio** [comment]
Ok, thanks. I was trying to map <p and >p to itself, like `map <nowait> <p <p` but it was not working. So I wanted to disable them, thanks!

**Comment by midnio** [comment]
It does not work, I disabled them but already waits.
