### ISSUE TITLE
=P using previous line's indent instead of current one

### ISSUE THREAD

**Issue by Gokuroro** [tpope/vim-unimpaired#167]
When using <p, >p, <P, >P and =p, the indent used as reference for all of the puts are the current line's indent (regardless of it being an Above or Below put).
When running the =P, on the other hand, the indent used is the one from the previous line.

Edit: Looks like removing the final ='] for the =P fixes the issue for me. Not sure if that's related to some configuration on my side for indents.

**Comment by tpope** [comment]
The way `=` works is it calls a function to determine the correct indent, and most indenting algorithms by necessity do this by looking at the line before. It sounds like what you want is `[p` and `]p`, which don't invoke `=` afterwards.

**Comment by Gokuroro** [comment]
That makes a lot of sense, I was thinking of = as "same" indent instead of running the = command after putting.
Thanks for clarifying!
