### ISSUE TITLE
[x does not encode ' (apostrophe)

### ISSUE THREAD

**Issue by WhoMeNope** [tpope/vim-unimpaired#174]
As far as I know the `'` should be encoded as `&apos;` or `&#39;` (for pre-html5 compatibility), however `[x` ignores the character.

Let me know if I am missing something, or if there is a reason behind this.

**Comment by tpope** [comment]
The short answer is that this plugin is older than HTML5, `&#39;` is ugly and confusing, and it didn't really seem necessary. I suppose given that it's 2019 I would be okay with encoding to `&apos;`.

**Comment by WhoMeNope** [comment]
Also how about expanding the encode to include all possible characters, since decode already supports them. 
To make the encode/decode symmetrical.

**Comment by tpope** [comment]
Now that's an argument you should have made back in 2009. Who is still writing `resum&eacute;` in this day and age?
