### ISSUE TITLE
Losing ">>" when remapping <,> to [,]

### ISSUE THREAD

**Issue by CharlesB2** [tpope/vim-unimpaired#176]
Using a non-US keyboard, I followed the adivce in the README to get <> instead of [] for calling unimpaired:
```
nmap < [
nmap > ]
...
```

Now I lost the ability to indent the current line with `>>`, which gets mapped to `]]`, I suppose. I tried to map `>>` to the vim "indent current line" command, but couldn't find how.

(Sorry if it's a bit off-topic, but I thing it's still related to the use of this great plugin)

**Comment by tpope** [comment]
You can do `nnoremap << <<` or `nnoremap [[ <<`, depending on your goals.
