### ISSUE TITLE
'co' mapping introduces delay for custom 'c' mapping

### ISSUE THREAD

**Issue by kerneis** [tpope/vim-unimpaired#180]
(This is an issue with how vim-unimpaired interacts with my custom config, probably not something to fix on your end, but I hope you can help.)

Because I use a non-standard keyboard layout, I don't use hjkl to move around but ctsr, hence in my vimrc: `noremap c h`.

Enabling vim-unimpaired introduces an unbearable delay whenever I press `c` to move left, because of the `co` mapping (my understanding is that vim is waiting for a `o` to happen, or not, before deciding to move).

I'm not an expert in vim mappings and my attempts at googling or fixing this issue have failed. Could you recommend something I'd add to my vimrc to avoid this unfortunate interaction?

In the meantime I've just removed the offending line from vim-unimpaired locally, but I'd rather have a fix that works with the upstream version. Thanks!

**Comment by tpope** [comment]
You can work around by adding `<nowait>` to your `c` map.
