### ISSUE TITLE
How to override lnext, lprev ... etc?

### ISSUE THREAD

**Issue by satshabad-cr** [tpope/vim-unimpaired#181]
It's annoying that with only one item in the quickfix window lnext will say "No Errors". I want to add the following bindings

```
command! Lnext try | lnext | catch | lfirst | catch | endtry
command! Lprev try | lprev | catch | llast | catch | endtry
```

So that when I hit `]l` it'll jump to the next one or the first one. How would I tell unimpaired to use those commands in lieu of the native lnext etc.

**Comment by MageJohn** [comment]
Why not use:
```vim
nmap <silent> [l :Lprev<CR>zv
nmap <silent> ]l :Lnext<CR>zv
```
This does nearly exactly the same thing as unimpaired's mapping, but with your command. If a map exists already then unimpaired won't overwrite it, so you get what you wanted. 

However I notice your commands don't take into account the `[range]` or `[!]` from :lprevious/:lnext; the mapping from unimpaired uses the count. Try this:
```vim
command! -range=1 -bang Lnext try | <count>lnext<bang> | catch /E553/ | lfirst<bang> | endtry
command! -range=1 -bang Lprev try | <count>lprev<bang> | catch /E553/ | llast<bang> | endtry

nmap <silent> [l :<C-U>exe (v:count ? v:count : "")."Lprev"<CR>zv
nmap <silent> ]l :<C-U>exe (v:count ? v:count : "")."Lnext"<CR>zv
```
Now the mapping works exactly the same way as unimpaired, except the location list wraps. I also added a pattern to the catch statement, just in case another error arises that the catch masks; feel free to remove it if you'd like, though I wouldn't recommend it.

**Comment by tpope** [comment]
Those maps seem like the right approach.

Note that the use of `<count>` in that replacement will not do what one would expect if you do `:2Lnext` on the last entry. But the count support isn't that useful in the real world; probably fine to omit it.

**Comment by MageJohn** [comment]
Good point; if you did want to use the count you could do this:
```vim
command! -range=1 -bang Lnext try | <count>lnext<bang> | catch /E553/ | lfirst<bang> <count> | endtry
```
With a smiliar modification to the Lprev.

**Comment by tpope** [comment]
That still won't do what I would expect if you call `:2Lnext` on the next to last item.
