### ISSUE TITLE
Consider making =p and friends retroactive

### ISSUE THREAD

**Issue by tylerbrazier** [tpope/vim-unimpaired#185]
Since `=p` and friends are still experimental, would you consider changing their functionality to retroactively indent after put (``=`]``)? That way you don't need to think about needing to hit `=` before `p`, but can `=p` after putting text that needs indent. I think `>p` would work similarly. This would also solve #183 

At least, `=p` shouldn't interfere with custom maps from .vimrc

**Comment by tpope** [comment]
So `=']` would work on any change, not just pastes. I would consider that a feature, not a bug, but I don't think it would be a good fit for the `=p` map.

You can generalize your desired behavior to an omap that works with any operator. The following makes `=x`, `<x`, `>x`, and every other operator target the most recent change:

    onoremap x :<C-U>normal! `[v`]<CR>

As much as I like this, I don't think this falls under the purview of unimpaired.vim.
