### ISSUE TITLE
`]z` `[z` for jumping between closed folds

### ISSUE THREAD

**Issue by hupfdule** [tpope/vim-unimpaired#188]
I would be nice if vim-unimpaired would support mappings to jump to the next / previous closed fold.

I would image `]z` and `[z` are a good fit, since `z` is used for fold commands.
Maybe an uppercase `]Z` / `[Z` could be used for jumping to the next fold, regardles of it being open or closed, but I am not sure if such a thing is possible in vim.

**Comment by tpope** [comment]
These are already built-ins for jumping to the start/end of the current fold. And `zk`/`zj` jump between folds.
