### ISSUE TITLE
Add support for marks

### ISSUE THREAD

**Issue by jssee** [tpope/vim-unimpaired#196]
It would be nice to have something like `[m` and `]m` for cycling through marks in a buffer, and perhaps capital `M` variants too.

**Comment by iforwms** [comment]
These are already bound by default in vim.

[m / [M | Jump to beginning/end next of method
]m / ]M | Jump to beginning/end of previous method

**Comment by tpope** [comment]
More generally, the number of remaining free maps is small, and thus the value of any new ones I'm willing to consider must be extremely high. I don't think mark cycling makes the cut. It's not even clear to me which set of marks to include.

* The letter marks? Feels low value. If you went to the trouble of assigning a letter you'd probably be better served by just jumping to it directly.
* The weird ones like `['` and `[^`? I think this would be confusing without a companion plugin like ShowMarks to see where you'd jump to. And if you do have a companion plugin installed, that plugin would be in a much better position to provide such maps.
