### ISSUE TITLE
Base 64 encode / decode

### ISSUE THREAD

**Issue by Jab2870** [tpope/vim-unimpaired#206]
Hi, thanks for creating this plugin. It's incredibly useful. Would you consider adding support for base64 encoding  / decoding? I was thinking `[b` and `]b` are probably logical mappings?

**Comment by tpope** [comment]
A pure VimL implementation seems like it would be unusably slow (at least until Vim 9 ships). And `[b`/`]b` are already taken by `:bprevious`/`:bnext` (which are admittedly extremely low value). That's a "no" for now.

**Comment by Jab2870** [comment]
That's a shame, thanks for responding though. Those reasons make sense.

**Comment by jmdevin** [comment]
Vim has `base64_encode` too as of [9.1.980](https://github.com/vim/vim/commit/810785c6890ef0a1cd2428410c8488cacfbac77b). I don't need this feature, but just so it's known.

**Comment by tpope** [comment]
Neither here nor there but that function is weird, as it only accepts a blob, and there's no way to get text from the current buffer as a blob. The closest you can do that I can find is `base64_encode(list2blob(str2list(join(getline(1, '$'), "\n"))))`, a ridiculous Rube Goldberg machine that doesn't even handle nulls correctly.

I guess what's actually weird is blobs, full stop. It's like someone went out of their way to make them impossible to work with.

**Comment by jmdevin** [comment]
I didn't even check to see if the functions had been implemented differently from neovim; I just assumed this was ported over by zeertz or someone. That is weird.

FWIW, it looks like someone else figured out the same issue: [link](https://github.com/vim/vim/issues/16392). The examples in the help docs now use `str2blob()` and `blob2str()`, which were only introduced in [9.1.1016](https://github.com/vim/vim/commit/1aefe1de0b20fe4966863e07efa14b6aa87323ee) in January and had a memory leak until [9.1.1035](https://github.com/vim/vim/commit/90b397586decc3751f92fd2f84271a6b431b56bc) a few days later.

**Comment by tpope** [comment]
Oh thanks, I've been annoyed at the blob stuff for years (but not annoyed enough to open an issue) and didn't catch there was a recent development.
