### ISSUE TITLE
Commit 77a878c4b0 causes (at least) NeoVim 0.5 and 0.6 to hang on startup.

### ISSUE THREAD

**Issue by andrewferrier** [tpope/vim-unimpaired#219]
I've been using `vim-unimpaired` for a while with both Vim and NeoVim at various versions. It works well.

The very recent commit 77a878c4b0 (about 45 mins ago) is causing hangs on both NeoVim 0.5 (released version) and 0.6 on startup - the welcome screen simply never displays. I narrowed it down to this one with a bisect.

I haven't yet had an opportunity to test this on Vim itself.

Thanks for your great work on these plugins!

**Comment by adriafarres** [comment]
This happens on vim as well.

**Comment by camilledejoye** [comment]
Two errors:
* the function `s:maps` is defined twice
* an extra `endif` was added when updating the condition line 41

**Comment by Serene-Arc** [comment]
I get this as well with Vim 8.2 from the Arch repository. Resetting the plugin to the commit before this one fixes the issue.

**Comment by tpope** [comment]
I would request that Arch distribute officially released versions only. If you're using a proper package manager, you shouldn't have to deal with getting stepped on by my clown shoes.

**Comment by Serene-Arc** [comment]
Oh no, I meant I'm using Vim from the arch repository in case the version helped; I'm using this plugin without the package manager, and the vim bundle folder is on the list of auto-updating repositories I have. Nothing to do with any official packages for this plugin :)

**Comment by tpope** [comment]
Never mind then!
