### ISSUE TITLE
[n / ]n mappings in visual mode

### ISSUE THREAD

**Issue by BenBergman** [tpope/vim-unimpaired#22]
[n and ]n for jumping to next VCS conflict marker does not seem to work in visual mode.

**Comment by glittershark** [comment]
hard yo is right. Just tried to implement this and I'm baffled as to how to prevent leaving visual mode. Ugh, vimscript

**Comment by blueyed** [comment]
https://github.com/tpope/vim-unimpaired/pull/187 does it for Neovim.

**Comment by tpope** [comment]
I assume I was trying to add more nuanced behavior the first time around because making a normal mode map work in visual mode is pretty straightforward.
