### ISSUE TITLE
Is it possible to make [<Space> jump to the new line and enter insert mode (like the 'o' key)?

### ISSUE THREAD

**Issue by lucas-salas** [tpope/vim-unimpaired#226]
If it's possible, which file would I need to edit to modify the command (I'm using neovim with zsh)? I'm a vim noob so I'll take as much instruction as someone is willing to give. 

Thanks!

**Comment by tpope** [comment]
There is no support for this. Maybe just use the `o` key?

**Comment by lucas-salas** [comment]
Just realized capital `O` is what I'm looking for, sorry!
