### ISSUE TITLE
Add filtering for [f and ]f

### ISSUE THREAD

**Issue by casr** [tpope/vim-unimpaired#229]
I have found `[f` and `]f` for jumping around and discovery are really useful for me within a project.

I would like to propose a filter on top of this to ignore certain other files. Generally speaking, I would like to filter out binary files but practically this could be implemented as just filtering out several well-known binary formats. It looks like there is already some of this happening in the `s:entries` function:

https://github.com/tpope/vim-unimpaired/blob/efdc6475f7ea789346716dabf9900ac04ee8604a/plugin/unimpaired.vim#L85-L86

Is this a feature that would be desirable?

**Comment by justinmk** [comment]
@casr that is what 'suffixes' is for. You should set that option (which will affect other Vim features such as completion, as well as plugins like vim-dirvish).

**Comment by casr** [comment]
Ah! Definitely misunderstood what `suffixes` was doing there. So it should be as simple as:

```vim
set suffixes+=.DS_Store,.gif,.jpg,.jpeg,.png,etc
```

Thanks!

Here is the related help for others who come across this issue. [`:h 'suffixes'`](https://vimhelp.org/options.txt.html#%27suffixes%27)

```help
'suffixes' 'su'		string	(default ".bak,~,.o,.h,.info,.swp,.obj")
			global
	Files with these suffixes get a lower priority when multiple files
	match a wildcard.  See |suffixes|.  Commas can be used to separate the
	suffixes.  Spaces after the comma are ignored.  A dot is also seen as
	the start of a suffix.  To avoid a dot or comma being recognized as a
	separator, precede it with a backslash (see |option-backslash| about
	including spaces and backslashes).
	See 'wildignore' for completely ignoring files.
	The use of |:set+=| and |:set-=| is preferred when adding or removing
	suffixes from the list.  This avoids problems when a future version
	uses another default.

						*'suffixesadd'* *'sua'*
'suffixesadd' 'sua'	string	(default "")
			local to buffer
	Comma-separated list of suffixes, which are used when searching for a
	file for the "gf", "[I", etc. commands.  Example: >
		:set suffixesadd=.java
```
