### ISSUE TITLE
`[u` doesn’t properly handle multi-byte characters

### ISSUE THREAD

**Issue by 8573** [tpope/vim-unimpaired#51]
`[u` doesn’t handle multi-byte characters in any semblance of a correct manner — e.g., it percent-escapes `—` (U+2014 EM DASH) as `%2014`, rather than, e.g., percent-escaping it as `%E2%80%94` (UTF-8, as JavaScript’s `encodeURI` function does) or simply raising an error.

**Comment by SolaWing** [comment]
this problem is still exist. 

by the way, I want to reuse `UnimpairedMapTransform` to override url encode with mine correct implement, but the key map is add to `s:maps`, and won't execute. any way to reuse `UnimpairedMapTransform` define custom mapping?

**Comment by tpope** [comment]
It should be possible to, yes. If you have a correct implementation though I'd rather make it official.

**Comment by SolaWing** [comment]
my correct implementation is call the python api…

**Comment by SolaWing** [comment]
@tpope good work! but now url_decode can't convert str back

**Comment by tpope** [comment]
Dang, that one's a bit less obvious. Any one have a better idea than fully re-implementing UTF-8 encoding?
