### ISSUE TITLE
Add `[ob`, `]ob`, and `cob` mapping for background switching

### ISSUE THREAD

**Issue by wbolster** [tpope/vim-unimpaired#58]
Please add `[ob`, `]ob`, and `cob` mappings to toggle between dark and light backgrounds. These commands would switch between`set background=dark` and `set background=light`, and reload the color scheme afterwards, e.g. using something like this:

``` viml
if exists("g:colors_name")
    exe "colorscheme " . g:colors_name
endif
```

(Example taken from the togglebg plugin in the vim-solarized color scheme.)

**Comment by NLKNguyen** [comment]
I need help on this https://github.com/tpope/vim-unimpaired/issues/100
