### ISSUE TITLE
Add '[o|', ']o|', and 'co|' mappings for colorcolumn=81 toggling

### ISSUE THREAD

**Issue by kiryph** [tpope/vim-unimpaired#61]
Sometimes I like to toggle the 'colorcolumn=81'. Do you like adding this to 'unimpaired.vim'?

``` diff
diff --git a/doc/unimpaired.txt b/doc/unimpaired.txt
index 4fa79f7..f1c206c 100644
--- a/doc/unimpaired.txt
+++ b/doc/unimpaired.txt
@@ -83,6 +83,7 @@ On    Off     Toggle  Option
 *[or*  *]or*   *cor*   'relativenumber'
 *[os*  *]os*   *cos*   'spell'
 *[ou*  *]ou*   *cou*   'cursorcolumn'
+*[oU*  *]oU*   *coU*   'colorcolumn=80'
 *[ov*  *]ov*   *cov*   'virtualedit'
 *[ow*  *]ow*   *cow*   'wrap'
 *[ox*  *]ox*   *cox*   'cursorline' 'cursorcolumn' (x as in crosshairs)
diff --git a/plugin/unimpaired.vim b/plugin/unimpaired.vim
index 1c9993b..b729410 100644
--- a/plugin/unimpaired.vim
+++ b/plugin/unimpaired.vim
@@ -214,6 +214,9 @@ nnoremap ]ob :set background=dark<CR>
 nnoremap cob :set background=<C-R>=&background == 'dark' ? 'light' : 'dark'<CR><CR>
 call s:option_map('c', 'cursorline')
 call s:option_map('u', 'cursorcolumn')
+nnoremap [oU :set colorcolumn=81<CR>
+nnoremap ]oU :set colorcolumn=0<CR>
+nnoremap coU :set colorcolumn=<C-R>=&colorcolumn != 0 ? 0 : 81<CR><CR>
 nnoremap [od :diffthis<CR>
 nnoremap ]od :diffoff<CR>
 nnoremap cod :<C-R>=&diff ? 'diffoff' : 'diffthis'<CR><CR>
```

**Comment by kiryph** [comment]
I add here an updated diff using `<bar>` for the mapping, `+1` as value for `colorcolumn` and it does not override additionally defined colorcolumns; it just adds or removes the value `+1` from `colorcolumn`:

```diff
❯ git diff
diff --git a/doc/unimpaired.txt b/doc/unimpaired.txt
index e5348b0..3e87f53 100644
--- a/doc/unimpaired.txt
+++ b/doc/unimpaired.txt
@@ -84,6 +84,7 @@ On    Off     Toggle  Option
 *[or*  *]or*   *cor*   'relativenumber'
 *[os*  *]os*   *cos*   'spell'
 *[ou*  *]ou*   *cou*   'cursorcolumn'
+*[o|*     *]o|*     *co|*     'colorcolumn' (+1)
 *[ov*  *]ov*   *cov*   'virtualedit'
 *[ow*  *]ow*   *cow*   'wrap'
 *[ox*  *]ox*   *cox*   'cursorline' 'cursorcolumn' (x as in crosshairs)
diff --git a/plugin/unimpaired.vim b/plugin/unimpaired.vim
index ac85503..799d63b 100644
--- a/plugin/unimpaired.vim
+++ b/plugin/unimpaired.vim
@@ -219,6 +219,9 @@ nnoremap ]ob :set background=dark<CR>
 nnoremap cob :set background=<C-R>=&background == 'dark' ? 'light' : 'dark'<CR><CR>
 call s:option_map('c', 'cursorline', 'setlocal')
 call s:option_map('u', 'cursorcolumn', 'setlocal')
+nnoremap [o<bar> :set colorcolumn+=+1<CR>
+nnoremap ]o<bar> :set colorcolumn-=+1<CR>
+nnoremap co<bar> :set colorcolumn<C-R>=match(&colorcolumn,'+1')>=0?'-=+1':'+=+1'<CR><CR>
 nnoremap [od :diffthis<CR>
 nnoremap ]od :diffoff<CR>
 nnoremap cod :<C-R>=&diff ? 'diffoff' : 'diffthis'<CR><CR>
```

**Comment by amigrave** [comment]
I don't know vim internals enough but I was wondering: is it possible to set the colorcolumn's value to the current column where the cursor is ?

So basically you would place your cursor at eg: line 120, use the toggler shortcut and it would `colorcolumn+=120`. Using the toggler again on the line would `colorcolumn-=120` and using the toggler at the beginning of a line would `colorcolumn=0` and disable them.

I'd like to add that to my vimrc but I have no idea if it's even possible, any idea !?

**Comment by wellle** [comment]
@amigrave: It is possible to get the current cursor column. Try this for example:
```vim
:echo getcurpos()[4]
```

**Comment by Asheq** [comment]
Instead of hard-coding the colorcolumn value to 81 (or any other number), I think we should read the value of **textwidth** (which the user can set to his preference).

    nnoremap [ot :set colorcolumn=<C-R>=&textwidth + 1<CR><CR>
    nnoremap ]ot :set colorcolumn=0<CR>
    nnoremap cot :set colorcolumn=<C-R>=&colorcolumn != 0 ? 0 : &textwidth + 1<CR><CR>

textwidth seems to me like the most useful place to have a colorcolumn. For reference, textwidth is the "maximum width of text that is being inserted.  A longer line will be broken after white space to get this width.  A zero value disables this." Where else would you put a colorcolumn?

**Comment by kiryph** [comment]
`:set colorcolumn+=+1<CR>` is the same as `:set colorcolumn=<C-R>=&textwidth + 1<CR><CR>`

**Comment by Asheq** [comment]
Ah I see, thanks. In this case, I endorse your mappings! (although, I personally would like to use `t` as the suffix instead of `bar` since it's easier to type).

**Comment by tpope** [comment]
`yot`
