### ISSUE TITLE
Automatically select current item in quickfix / location list, if there's only one

### ISSUE THREAD

**Issue by blueyed** [tpope/vim-unimpaired#7]
I think the `:lnext`, `:lprev`, `:cnext` and `:cprev` mappings should catch any "E553 No more items" error and execute `:ll` or `:cc` automatically.

The idea appeared from the report at: https://github.com/scrooloose/syntastic/issues/32

**Comment by eggers** [comment]
@tpope I'd like this as well. As a separate shortcut it would be fine as well.

**Comment by timblaktu** [comment]
For those stumbling on this behavior, see [this workflow/workaround](https://stackoverflow.com/a/15417309).
