### ISSUE TITLE
blankup/down on readonly file

### ISSUE THREAD

**Issue by ghost** [tpope/vim-unimpaired#88]
Unimpaired should handle readonly files better. When I try to add a blank line to a readonly file I get this:

```
Error detected while processing function <SNR>84_BlankUp:
line    1:W10: Warning: Changing a readonly file
Press ENTER or type command to continue
```

It's not uncommon to edit readonly files and then use SudoWrite from your Eunich plugin.

**Comment by blueyed** [comment]
I think this warning is useful and what I would expect: it just like when editing the file normally, isn't it?

**Comment by tpope** [comment]
It should be less noisy about it, but yeah, the warning itself should stay.
