### ISSUE TITLE
DOS line endings?

### ISSUE THREAD

**Issue by ezuk** [tpope/vim-unimpaired#91]
Hi,

This is very likely an issue on my end and not with the repo, I'm just not sure what caused it. When installing Unimpaired on Vim 7.4 under Ubuntu 14.04 with Vundle, the entire repo came with ^M (DOS) line endings.

I was able to fix the plugin file, but the help contents has DOS line endings as well... Any idea what might have caused this?

**Comment by tpope** [comment]
My guess would be one of those dos line ending options in your git config.

**Comment by ezuk** [comment]
Must be SPF13-related, then... Thanks Tim.
