### ISSUE TITLE
Conflict marker searching in normal mode broken

### ISSUE THREAD

**Issue by awood** [tpope/vim-unimpaired#98]
I'm using the Fedora 22 stock version of Vim (7.4 Included patches: 1-207, 209-640)

In Fedora 20 (7.4 Included patches: 1-207, 209-475), the `[n` and `]n` mappings work fine in normal mode.  In F22, they fail.

The regex used (`^@@ .* @@\|^[<=>|]\{7}[<=>|]\@!`) matches just fine in Fedora 20, but in Fedora 22, the behavior/precedence of some of the regex operators seems to have changed.  If I set the regex to `\(^@@ .* @@\)\|\(^[<=>|]\{7}[<=>|]\@!\)` everything works.

I will be happy to submit a PR with this minor fix, but I don't know if the `ContextMotion` function needs the grouping parenthesis added as well.  The `<motion>]n` appears to be working just fine.

**Comment by tpope** [comment]
That's a pretty huge change if true. Can you check if changing the value of `'regexpengine'` also fixes it?

**Comment by awood** [comment]
Neither setting makes a difference.  Looking at ftp://ftp.vim.org/pub/vim/patches/7.4/README I see a few interesting patches between 475 and 640:

```
118187  7.4.497  NFA engine is very slow with some regexp patterns
  3709  7.4.527  still confusing regexp failure and NFA_TOO_EXPENSIVE
  6713  7.4.613  the NFA engine does not implement the 'redrawtime' time limit
```

I did a quick diff on the version output from F20 and F22 and the only differences were `+lua/dyn` instead of `+lua`, the `-Werror=format-security` compile flag, and `-L/usr/local/lib` added to the linker flags.

**Comment by awood** [comment]
With Vim v7-4-640 compiled from source, the problem does not manifest so this is likely a packaging error/issue with Fedora.

**Comment by tpope** [comment]
Can you tell me if the slightly simplified `^\(^@@ .* @@\|[<=>|]\{7}[<=>|]\@!\)` also works?

**Comment by awood** [comment]
> Can you tell me if the slightly simplified ^\(^@@ .* @@\|[<=>|]\{7}[<=>|]\@!\) also works?

Yes, that works just fine.  I'm filing a Fedora bug and I'll link it here when it's in.

**Comment by awood** [comment]
Filed as https://bugzilla.redhat.com/show_bug.cgi?id=1241233

**Comment by tpope** [comment]
Err drop that second caret and update the pull request and I'll merge.
